### ISSUE TITLE
建议增加背景信息功能

### ISSUE THREAD

**Issue by dyxang** [easychen/h2webreader#1]
就是背景音一样的东西……
类似于qq群里“xx已加入群”“xx送xx礼物”“xx被禁言xx天”那种透明居中小方框。
可用于旁白和人物心理或者神态描写
------
update
好吧我发现有这个功能……

**Comment by dyxang** [comment]
小白问一下能自定义界面吗？

**Comment by easychen** [comment]
可以直接修改和覆盖现有CSS样式。

**Comment by dyxang** [comment]
@easychen  但是我在 h2webreader\src\reader.js 的第136行中
把 ✦ 替换成了 img 标签，complie不出来，显示错误

**Comment by easychen** [comment]
> @easychen 但是我在 h2webreader\src\reader.js 的第136行中
> 把 ✦ 替换成了 img 标签，complie不出来，显示错误

那不是样式，是JSX。首先你要会语法……

**Comment by dyxang** [comment]
> > @easychen 但是我在 h2webreader\src\reader.js 的第136行中
> > 把 ✦ 替换成了 img 标签，complie不出来，显示错误
> 
> 那不是样式，是JSX。首先你要会语法……

意思是我只要这样`<img src={require('图片地址')} />`，就可以了吧？
